import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaEllipse bg circle
    Autogenerated by FlutLab FTF Generator
  */
class BgcircleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 462.0,
      height: 462.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M462 231C462 358.578 358.578 462 231 462C103.422 462 0 358.578 0 231C0 103.422 103.422 0 231 0C358.578 0 462 103.422 462 231Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
