import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/Ellipse10Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/Rectangle21Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/Ellipse11Widget.dart';

/* FigmaGroup dot
    Autogenerated by FlutLab FTF Generator
  */
class DotWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 65.71428680419922,
      height: 10.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 10.0,
            height: 10.0,
            child: Ellipse10Widget(),
          ),
          Positioned(
            left: 20.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 10.0,
            height: 10.0,
            child: Ellipse11Widget(),
          ),
          Positioned(
            left: 40.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 25.714284896850586,
            height: 10.0,
            child: Rectangle21Widget(),
          )
        ]),
      ),
    );
  }
}
