import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/IconWidget2.dart';
import 'package:flutterapp/figma/splash2widget/widgets/PesankuWidget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/TextWidget8.dart';

/* FigmaGroup logo
    Autogenerated by FlutLab FTF Generator
  */
class LogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 272.0,
      height: 100.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 96.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 113.0,
            height: 35.0,
            child: PesankuWidget(),
          ),
          Positioned(
            left: 52.0,
            top: 3.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: IconWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: 60.0,
            right: null,
            bottom: null,
            width: 272.0,
            height: 40.0,
            child: TextWidget8(),
          )
        ]),
      ),
    );
  }
}
