import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget35 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.313168525695801,
      height: 21.45093536376953,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.816326 21.3643C0.816326 21.2325 2.39867 20.9687 4.9041 20.705C5.56342 20.705 6.22279 20.5731 6.35466 20.0457C6.48652 19.5182 6.22273 18.8589 5.959 18.0677C5.43154 16.4853 4.77227 14.7711 4.11294 13.0568C1.60751 5.93615 -0.238639 0.134119 0.0250901 0.00225412C0.288819 -0.129611 2.66242 5.54056 5.16784 12.6612C5.82717 14.3755 6.35461 16.0897 6.88207 17.6721C7.1458 18.4633 7.54141 19.2545 7.14581 20.1775C7.01395 20.705 6.48651 20.9687 6.09091 21.1006C5.69532 21.2325 5.29974 21.2324 5.03601 21.2324C2.39872 21.4962 0.816326 21.4962 0.816326 21.3643Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
