import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 4.747175693511963,
      height: 4.483389854431152,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M4.74718 2.10982C4.74718 3.2966 3.69227 4.35153 2.37363 4.48339C1.05498 4.48339 0 3.56035 0 2.37357C0 1.18679 1.05498 0.131865 2.37363 0C3.69227 0 4.74718 0.92304 4.74718 2.10982Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
