import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget40 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 5.274585723876953,
      height: 5.274585723876953,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.63729 5.27459C4.09383 5.27459 5.27459 4.09383 5.27459 2.63729C5.27459 1.18076 4.09383 0 2.63729 0C1.18076 0 0 1.18076 0 2.63729C0 4.09383 1.18076 5.27459 2.63729 5.27459Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
