import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget20 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 65.40483093261719,
      height: 65.40485382080078,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M32.7024 65.4049C50.7635 65.4049 65.4048 50.7635 65.4048 32.7024C65.4048 14.6414 50.7635 0 32.7024 0C14.6414 0 0 14.6414 0 32.7024C0 50.7635 14.6414 65.4049 32.7024 65.4049Z')
          ..color = Color.fromARGB(255, 245, 245, 245),
      ]),
    );
  }
}
