import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 118.28704833984375,
      height: 149.22967529296875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M14.188 15.2294C28.825 -4.02284 44.1213 -1.25369 54.8023 3.36158C65.4834 7.97684 72.6041 19.7128 71.9447 31.3169C71.8129 34.3498 71.1536 37.6464 72.3404 40.4156C74.3184 44.8989 80.1204 46.2176 83.5489 49.7779C88.1642 54.6569 87.1092 62.5688 85.5269 69.0302C83.9445 75.6234 82.3621 83.1397 86.1862 88.678C89.7465 93.6889 96.4716 95.1394 102.01 97.7767C109.394 101.337 115.328 108.062 117.438 115.842C119.548 123.754 117.702 132.721 112.163 138.787C106.757 144.72 98.5814 147.358 90.6695 148.413C67.5932 151.841 43.1983 144.325 25.924 128.765C8.64976 113.073 -0.976406 89.4692 0.0785108 66.261')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
