import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget38 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.648577690124512,
      height: 3.322589159011841,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M11.6288 2.01157C11.3651 2.6709 8.85969 2.2753 5.8268 2.6709C2.79391 2.93463 0.420317 3.72582 0.0247232 3.06649C-0.107141 2.80277 0.288485 2.14343 1.21154 1.4841C2.13459 0.824779 3.71695 0.165468 5.56305 0.0336036C7.40916 -0.0982611 8.99157 0.165468 10.0465 0.692927C11.2333 1.08852 11.7607 1.74784 11.6288 2.01157Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
