import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget39 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.834317207336426,
      height: 2.998969554901123,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M8.73541 2.76915C8.33982 3.2966 6.49373 2.76916 4.3839 2.63729C2.27406 2.50543 0.427973 2.90101 0.0323787 2.37355C-0.099486 2.10982 0.164259 1.45051 0.955447 0.923049C1.74664 0.39559 3.06522 0 4.51573 0C5.96624 0.131865 7.15307 0.659315 7.94426 1.18677C8.73545 1.97796 8.99914 2.50542 8.73541 2.76915Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
