import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/BackgroundCompleteWidget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/Character3Widget.dart';

/* FigmaGroup vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget43 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 266.2719421386719,
      height: 334.2270812988281,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.6358692220085754;

              double height = constraints.maxHeight * 0.23913951694277724;

              return Stack(children: [
                Transform(
                  transform:
                      Matrix4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: BackgroundCompleteWidget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.9445338152172804;

              double height = constraints.maxHeight * 0.765789215859491;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.05546622059852159,
                      constraints.maxHeight * 0.2342107613135301,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: Character3Widget(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
