import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget34 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.427164077758789,
      height: 2.557354211807251,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M9.3942 2.52248C9.13047 2.78621 7.28436 1.46758 4.77893 1.46758C2.2735 1.33571 0.295567 2.65436 0.031838 2.39063C-0.100027 2.25876 0.163687 1.7313 1.08674 1.07198C1.87793 0.544523 3.32839 -0.114804 4.91077 0.0170604C6.49314 0.0170604 7.81185 0.676384 8.60304 1.33571C9.26236 1.7313 9.52606 2.25875 9.3942 2.52248Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
