import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget36 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.33399772644043,
      height: 7.384428024291992,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.422119 0C0.817712 0 0.817713 2.76917 3.05941 4.74714C5.43298 6.7251 8.334 6.46136 8.334 6.85696C8.334 6.98882 7.67464 7.38443 6.48786 7.38443C5.30108 7.38443 3.45499 6.98882 2.13634 5.80204C0.685832 4.61525 0.158405 2.90101 0.0265406 1.8461C-0.105324 0.659315 0.290254 0 0.422119 0Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
