import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID87Widget.dart';

/* FigmaGroup XMLID 86
    Autogenerated by FlutLab FTF Generator
  */
class XMLID86Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.948174953460693,
      height: 7.326037406921387,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.2608782381602794;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 10.02168083190918;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.10799230907117204;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.7911556959152222;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9330507889387493,
                      constraints.maxHeight * 0.9999993491199516,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID87Widget(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
