import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 127
    Autogenerated by FlutLab FTF Generator
  */
class XMLID127Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.578863143920898,
      height: 8.1895112991333,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0.00766867C0.131865 -0.124196 2.37361 1.45818 4.74718 3.69988C7.12074 5.94158 8.70307 8.18327 8.5712 8.18327C8.43934 8.31514 6.59325 6.33718 4.21968 4.09548C1.97799 1.98565 0 0.139533 0 0.00766867Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
