import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID220Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID213Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID168Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID216Widget.dart';

/* FigmaGroup XMLID 167
    Autogenerated by FlutLab FTF Generator
  */
class XMLID167Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 91.33462524414062,
      height: 121.9913101196289,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.656502967235611;

              double height = constraints.maxHeight * 0.9595198642621522;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.34349703276438903,
                      constraints.maxHeight * 0.040480143555407265,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID168Widget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.6456511980374579;

              double height = constraints.maxHeight * 0.9207400789698583;

              return Stack(children: [
                Transform(
                  transform:
                      Matrix4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID213Widget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.12753736777249;

              double height = constraints.maxHeight * 0.027236277368884676;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.5655656993510874,
                      constraints.maxHeight * 0.15875719879959813,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID216Widget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.09672473263805473;

              double height = constraints.maxHeight * 0.024583468707404073;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.8527901303538797,
                      constraints.maxHeight * 0.1730848308389586,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID220Widget(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
