import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 75
    Autogenerated by FlutLab FTF Generator
  */
class XMLID75Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.90, -0.45, 0.00, 0.00, 0.45, -0.90, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 10.549171447753906,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.27459 0.791196C8.18766 0.791196 10.5492 0.614058 10.5492 0.395578C10.5492 0.177097 8.18766 0 5.27459 0C2.36151 0 0 0.177097 0 0.395578C0 0.614058 2.36151 0.791196 5.27459 0.791196Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
