import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 79
    Autogenerated by FlutLab FTF Generator
  */
class XMLID79Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.875696659088135,
      height: 7.794968605041504,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.86801 7.78666C6.73615 7.91852 4.89004 6.468 2.91207 4.35817C0.934103 2.11647 -0.12083 0.138518 0.0110342 0.00665304C0.142899 -0.125212 1.59346 1.72089 3.43956 3.96259C5.41753 6.07243 6.99988 7.65479 6.86801 7.78666Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
