import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID75Widget.dart';

/* FigmaGroup XMLID 74
    Autogenerated by FlutLab FTF Generator
  */
class XMLID74Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.797072410583496,
      height: 5.406959056854248,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0767677328135228;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 10.549171447753906;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.14632918813162993;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.7911959290504456;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9640300886549418,
                      constraints.maxHeight * 0.9999999118104737,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID75Widget(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
