import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID63Widget.dart';

/* FigmaGroup XMLID 62
    Autogenerated by FlutLab FTF Generator
  */
class XMLID62Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.457639694213867,
      height: 13.874841690063477,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.8397581862412018;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 15.560011863708496;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.05702378064731821;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.7911959290504456;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9999944748129274,
                      constraints.maxHeight * 0.028482785741612417,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID63Widget(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
