import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 99
    Autogenerated by FlutLab FTF Generator
  */
class XMLID99Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.51, 0.86, 0.00, 0.00, -0.86, -0.51, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 10.81291675567627,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.40642 0.791176C8.39232 0.791176 10.8129 0.614078 10.8129 0.395598C10.8129 0.177117 8.39232 0 5.40642 0C2.42052 0 0 0.177117 0 0.395598C0 0.614078 2.42052 0.791176 5.40642 0.791176Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
