import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 237
    Autogenerated by FlutLab FTF Generator
  */
class XMLID237Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 43.119754791259766,
      height: 58.2841682434082,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M43.1198 0C40.7462 4.61526 34.1529 7.51627 30.9882 12.659C28.3509 17.0105 27.4278 22.0214 25.8454 26.7685C21.4939 39.955 12.1315 51.4272 0 58.2842C2.37356 53.6689 4.35157 48.9218 5.80208 43.9109C6.4614 39.2957 4.48343 35.076 4.48343 35.076C5.93394 30.4607 12.659 23.9994 15.6919 20.1753C19.2523 15.56 22.9444 10.9447 27.4278 7.25254C31.9112 3.42846 37.3177 0.527459 43.1198 0Z')
          ..color = Color.fromARGB(255, 245, 245, 245),
      ]),
    );
  }
}
