import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 91
    Autogenerated by FlutLab FTF Generator
  */
class XMLID91Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.85, 0.52, 0.00, 0.00, -0.52, -0.85, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 12.13148307800293,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M6.06574 0.791196C9.41578 0.791196 12.1315 0.614099 12.1315 0.395618C12.1315 0.177138 9.41578 0 6.06574 0C2.71571 0 0 0.177138 0 0.395618C0 0.614099 2.71571 0.791196 6.06574 0.791196Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
