import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 111
    Autogenerated by FlutLab FTF Generator
  */
class XMLID111Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.36, 0.93, 0.00, 0.00, -0.93, -0.36, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 11.867817878723145,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.93391 0.791196C9.21112 0.791196 11.8678 0.614078 11.8678 0.395598C11.8678 0.177117 9.21112 0 5.93391 0C2.6567 0 0 0.177117 0 0.395598C0 0.614078 2.6567 0.791196 5.93391 0.791196Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
