import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID31Widget.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID33Widget.dart';

/* FigmaGroup XMLID 30
    Autogenerated by FlutLab FTF Generator
  */
class XMLID30Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 118.28704833984375,
      height: 149.22967529296875,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 1.0;

              double height = constraints.maxHeight * 1.0;

              return Stack(children: [
                Transform(
                  transform:
                      Matrix4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID31Widget(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.7058834683942075;

              double height = constraints.maxHeight * 0.936139328804051;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.21693174136939083,
                      constraints.maxHeight * 0.008018809287319031,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: XMLID33Widget(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
