import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 95
    Autogenerated by FlutLab FTF Generator
  */
class XMLID95Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.43, -0.90, 0.00, 0.00, 0.90, -0.43, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 11.604072570800781,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.802 0.791196C9.00638 0.791196 11.6041 0.614058 11.6041 0.395578C11.6041 0.177097 9.00638 0 5.802 0C2.59762 0 0 0.177097 0 0.395578C0 0.614058 2.59762 0.791196 5.802 0.791196Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
