import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 83
    Autogenerated by FlutLab FTF Generator
  */
class XMLID83Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.05907154083252,
      height: 8.058991432189941,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.00623854 8.04995C-0.125626 7.91809 1.85239 6.33571 4.09409 4.09401C6.33579 1.85231 7.7863 -0.125626 8.05003 0.00623878C8.1819 0.138103 6.8632 2.3798 4.6215 4.6215C2.3798 6.8632 0.138103 8.18182 0.00623854 8.04995Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
