import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 53
    Autogenerated by FlutLab FTF Generator
  */
class XMLID53Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.104474067687988,
      height: 1.8996248245239258,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.00586193 0.965216C-0.126003 0.833351 1.98383 -0.221582 4.62112 0.0421474C7.39028 0.305877 9.10447 1.75638 9.10447 1.88824C8.97261 2.02011 7.12655 0.965208 4.62112 0.833343C2.1157 0.437749 0.00586193 1.22895 0.00586193 0.965216Z')
          ..color = Color.fromARGB(255, 38, 50, 56),
      ]),
    );
  }
}
