import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/XMLID99Widget.dart';

/* FigmaGroup XMLID 98
    Autogenerated by FlutLab FTF Generator
  */
class XMLID98Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 6.223007678985596,
      height: 9.688525199890137,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.7375708521444198;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 10.81291675567627;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.0816611162542554;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 0.7911757826805115;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9999999233751294,
                      constraints.maxHeight * 0.04186765533157039,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID99Widget(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
