import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 165
    Autogenerated by FlutLab FTF Generator
  */
class XMLID165Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.93740463256836,
      height: 6.85695743560791,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M9.9374 0.395598C9.9374 0.527463 9.14618 0.395586 8.09127 0.527451C6.90449 0.659315 5.45401 1.05492 4.0035 1.97797C2.55298 2.90102 1.49808 4.21966 0.970625 5.14271C0.443166 6.06577 0.179421 6.85696 0.0475564 6.85696C-0.0843083 6.85696 0.0475886 6.06578 0.575047 5.01086C1.10251 3.95594 2.02554 2.50542 3.60792 1.4505C5.19029 0.395582 6.90449 0 8.09127 0C9.14618 0 9.9374 0.263733 9.9374 0.395598Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
