import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 87
    Autogenerated by FlutLab FTF Generator
  */
class XMLID87Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.74, -0.67, 0.00, 0.00, 0.67, -0.74, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 10.02168083190918,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M5.01084 0.791156C7.77826 0.791156 10.0217 0.614058 10.0217 0.395578C10.0217 0.177097 7.77826 0 5.01084 0C2.24342 0 0 0.177097 0 0.395578C0 0.614058 2.24342 0.791156 5.01084 0.791156Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
