import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 24
    Autogenerated by FlutLab FTF Generator
  */
class XMLID24Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.881103515625,
      height: 18.741722106933594,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M20.5625 1.46746C18.9801 -0.510514 15.9472 -0.378655 14.1011 1.20372C12.255 2.7861 11.332 4.63221 11.2001 7.2695C10.6726 4.63221 9.35399 3.04983 7.24416 1.73118C5.13433 0.412534 2.10141 0.676266 0.782759 2.91796C-0.0084284 4.23661 -0.140293 5.81899 0.123436 7.40136C0.387166 8.98374 0.914656 10.5661 1.96957 11.621C5.66178 15.4451 7.50786 16.1044 11.9913 18.7417C16.0791 15.577 17.3977 14.6539 20.5625 10.4342C21.4855 9.24746 21.7492 7.53323 21.8811 6.08272C21.8811 4.36848 21.4855 2.65424 20.5625 1.46746Z')
          ..color = Color.fromARGB(255, 245, 245, 245),
      ]),
    );
  }
}
