import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 147
    Autogenerated by FlutLab FTF Generator
  */
class XMLID147Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.977251052856445,
      height: 3.907503128051758,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M7.97725 3.9075C7.84539 3.9075 7.58167 3.51191 6.92235 2.85258C6.26303 2.19326 5.47179 1.27021 4.15314 0.874612C2.96636 0.479018 1.64776 0.874616 0.988441 1.27021C0.329118 1.79767 0.197237 2.32513 0.0653726 2.32513C-0.0664921 2.32513 -0.0664921 1.6658 0.724696 0.874612C1.38402 0.215289 2.96638 -0.312169 4.41689 0.215289C5.8674 0.742748 6.79047 1.79767 7.31793 2.58886C7.84539 3.24818 7.97725 3.77564 7.97725 3.9075Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
