import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash2widget/widgets/VectorWidget23.dart';
import 'package:flutterapp/figma/splash2widget/widgets/VectorWidget21.dart';
import 'package:flutterapp/figma/splash2widget/widgets/VectorWidget22.dart';
import 'package:flutterapp/figma/splash2widget/widgets/VectorWidget20.dart';

/* FigmaGroup XMLID 7
    Autogenerated by FlutLab FTF Generator
  */
class XMLID7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 65.40483093261719,
      height: 65.40485382080078,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 65.40483093261719;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 1.0;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 65.40485382080078;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget20(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.25927104186735117;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 16.957578659057617;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.21688621905818964;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.18541145324707;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.1484929355158478,
                      constraints.maxHeight * 0.3476300181563782,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget21(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.25944814389608367;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 16.969161987304688;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.21688621905818964;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.18541145324707;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.5900234720699632,
                      constraints.maxHeight * 0.33754937887456116,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget22(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.3286289555897051;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 21.493921279907227;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.15322580457018142;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 10.021711349487305;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.340724239689005,
                      constraints.maxHeight * 0.6149194336236526,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget23(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
