import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 49
    Autogenerated by FlutLab FTF Generator
  */
class XMLID49Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.92794418334961,
      height: 3.6734466552734375,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.00522464 3.64793C-0.12664 3.51606 2.24689 1.40624 6.07097 0.483183C9.76318 -0.439869 12.9279 0.219446 12.9279 0.35131C12.9279 0.61504 9.89506 0.219454 6.33471 1.14251C2.6425 2.06556 0.137089 3.91166 0.00522464 3.64793Z')
          ..color = Color.fromARGB(255, 38, 50, 56),
      ]),
    );
  }
}
