import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 151
    Autogenerated by FlutLab FTF Generator
  */
class XMLID151Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.384387969970703,
      height: 2.156182050704956,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 1.99846C0 1.99846 0.131832 1.471 0.791156 0.943543C1.45048 0.416084 2.50541 -0.11137 3.69219 0.0204942C4.87898 0.0204942 5.93391 0.547937 6.59323 1.0754C7.25256 1.60285 7.38439 1.99845 7.38439 2.13032C7.25252 2.26218 6.98881 1.86659 6.32949 1.47099C5.67016 1.0754 4.74711 0.81167 3.69219 0.81167C2.63728 0.81167 1.71422 1.20726 1.0549 1.47099C0.395578 1.73472 0 1.99846 0 1.99846Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
