import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 28
    Autogenerated by FlutLab FTF Generator
  */
class XMLID28Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 215.59869384765625,
      height: 198.98374938964844,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M116.173 0C82.811 0 53.2734 16.4831 35.3398 41.6692L0 46.6801L19.7797 74.8991C17.8017 82.811 16.7468 90.9866 16.7468 99.5578C16.7468 154.545 61.3171 198.984 116.173 198.984C171.16 198.984 215.599 154.414 215.599 99.5578C215.599 44.7021 171.028 0 116.173 0Z')
          ..color = Color.fromARGB(255, 245, 245, 245),
      ]),
    );
  }
}
