import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 139
    Autogenerated by FlutLab FTF Generator
  */
class XMLID139Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.09, 1.00, 0.00, 0.00, -1.00, -0.09, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 12.395309448242188,
          height: 1.0,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M6.19765 0.791196C9.62052 0.791196 12.3953 0.614099 12.3953 0.395618C12.3953 0.177138 9.62052 0 6.19765 0C2.77479 0 0 0.177138 0 0.395618C0 0.614099 2.77479 0.791196 6.19765 0.791196Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
