import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/ShapeWidget11.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/BoundsWidget11.dart';

/* FigmaGroup Add
    Autogenerated by FlutLab FTF Generator
  */
class AddWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 24.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: BoundsWidget11(),
          ),
          Positioned(
            left: 5.0,
            top: 5.0,
            right: null,
            bottom: null,
            width: 14.0,
            height: 14.0,
            child: ShapeWidget11(),
          )
        ]),
      ),
    );
  }
}
