import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector app bar bg
    Autogenerated by FlutLab FTF Generator
  */
class AppbarbgWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 80.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M360 0L0 0L0 80L360 80L360 0Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
