import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/MaggiePhillipsWidget1.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/IconsNavigation24pxWhiteMenuWidget1.dart';

/* FigmaGroup app bar contents
    Autogenerated by FlutLab FTF Generator
  */
class AppbarcontentsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 107.0,
      height: 24.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 56.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 51.0,
            height: 22.0,
            child: MaggiePhillipsWidget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: IconsNavigation24pxWhiteMenuWidget1(),
          )
        ]),
      ),
    );
  }
}
