import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Base
    Autogenerated by FlutLab FTF Generator
  */
class BaseWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 369.0,
      height: 76.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0L369 0L369 76L0 76L0 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
        SvgPathPainter.stroke(
          0.25,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M0 0L0 -0.25L-0.25 -0.25L-0.25 0L0 0ZM369 0L369.25 0L369.25 -0.25L369 -0.25L369 0ZM369 76L369 76.25L369.25 76.25L369.25 76L369 76ZM0 76L-0.25 76L-0.25 76.25L0 76.25L0 76ZM0 0.25L369 0.25L369 -0.25L0 -0.25L0 0.25ZM368.75 0L368.75 76L369.25 76L369.25 0L368.75 0ZM369 75.75L0 75.75L0 76.25L369 76.25L369 75.75ZM0.25 76L0.25 0L-0.25 0L-0.25 76L0.25 76Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
