import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/Mdi_attach_fileWidget1.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/FileWidget2.dart';

/* FigmaGroup file
    Autogenerated by FlutLab FTF Generator
  */
class FileWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 57.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: Mdi_attach_fileWidget1(),
          ),
          Positioned(
            left: 1.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 22.0,
            height: 24.0,
            child: FileWidget2(),
          )
        ]),
      ),
    );
  }
}
