import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/ImgWidget1.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/Friday1523Widget5.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/Group15Widget1.dart';

/* FigmaGroup #3
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 322.0,
      height: 112.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 52.0,
            top: 28.0,
            right: null,
            bottom: null,
            width: 270.0,
            height: 84.0,
            child: Group15Widget1(),
          ),
          Positioned(
            left: 124.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 16.0,
            child: Friday1523Widget5(),
          ),
          Positioned(
            left: 0.0,
            top: 28.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: ImgWidget1(),
          )
        ]),
      ),
    );
  }
}
