import 'package:flutter/material.dart';

/* FigmaText Friday・15:23
    Autogenerated by FlutLab FTF Generator
  */
class Friday1523Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Monday・11:11AM''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4545454545454546,
        fontSize: 11.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
