import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/TextWidget7.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/RectangleWidget5.dart';

/* FigmaGroup Group 15
    Autogenerated by FlutLab FTF Generator
  */
class Group15Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 270.0,
      height: 84.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 270.0,
            height: 84.0,
            child: RectangleWidget5(),
          ),
          Positioned(
            left: 16.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 238.0,
            height: 60.0,
            child: TextWidget7(),
          )
        ]),
      ),
    );
  }
}
