import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/BackWidget1.dart';

/* FigmaGroup Icons / Navigation 24px / White / Menu
    Autogenerated by FlutLab FTF Generator
  */
class IconsNavigation24pxWhiteMenuWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/PesanWidget'),
      child: Container(
        width: 24.0,
        height: 24.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: BackWidget1(),
                )
              ]),
        ),
      ),
    );
  }
}
