import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/VectorWidget11.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/VectorWidget12.dart';
import 'package:flutterapp/figma/pesan2widget/widgets/VectorWidget13.dart';

/* FigmaFrame mdi_photo_camera
    Autogenerated by FlutLab FTF Generator
  */
class Mdi_photo_cameraWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.0,
      height: 24.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.2666666507720947;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 6.399999618530273;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.2666666507720947;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 6.399999618530273;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.36666667461395264,
                      constraints.maxHeight * 0.36666667461395264,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget11(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.8333333333333334;
              double scaleX = (constraints.maxWidth * percentWidth) / 20.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.75;
              double scaleY = (constraints.maxHeight * percentHeight) / 18.0;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.08333333333333333,
                      constraints.maxHeight * 0.08333333333333333,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget12(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.0;
              double scaleX = (constraints.maxWidth * percentWidth) / 24.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 1.0;
              double scaleY = (constraints.maxHeight * percentHeight) / 24.0;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget13(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
