import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class RectangleWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 252.0,
      height: 58.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.95431 8.95431 0 20 0L232 0C243.046 0 252 8.95431 252 20L252 38C252 49.0457 243.046 58 232 58L20 58C8.9543 58 0 49.0457 0 38L0 20Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
