import 'package:flutter/material.dart';

/* FigmaText text
    Autogenerated by FlutLab FTF Generator
  */
class TextWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Dirumah mau ada acara syukuran, mau pulang ngga?''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3333333333333333,
        fontSize: 15.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
