import 'package:flutter/material.dart';

/* FigmaText Video
    Autogenerated by FlutLab FTF Generator
  */
class VideoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Video''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.7142857142857142,
        fontSize: 14.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
