import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Android2Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Android3Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/BGWidget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget130.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Android1Widget.dart';

/* FigmaFrame thumb1
    Autogenerated by FlutLab FTF Generator
  */
class Thumb1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1600.0,
      height: 1200.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
            child: null,
          ),
          Positioned(
            left: -56.0,
            top: -313.0,
            right: null,
            bottom: null,
            width: 1656.0,
            height: 1826.869873046875,
            child: BGWidget(),
          ),
          Positioned(
            left: 77.0,
            top: 97.0,
            right: null,
            bottom: null,
            width: 453.0,
            height: 805.0,
            child: Android1Widget(),
          ),
          Positioned(
            left: 1071.0,
            top: 297.0,
            right: null,
            bottom: null,
            width: 453.0,
            height: 805.0,
            child: Android3Widget(),
          ),
          Positioned(
            left: 574.0,
            top: 197.0,
            right: null,
            bottom: null,
            width: 453.0,
            height: 805.0,
            child: Android2Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.22977956771850586;

              double height = constraints.maxHeight * 0.42717549641927083;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.385,
                      constraints.maxHeight * 0.050833333333333335,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: VectorWidget130(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    ));
  }
}
