import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/VectorWidget131.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget30.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/Rectangle17Widget1.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/Rectangle15Widget1.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/VectorWidget192.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/Rectangle18Widget1.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget31.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget24.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/Ellipse3Widget1.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/Ellipse4Widget1.dart';

/* FigmaGroup BG
    Autogenerated by FlutLab FTF Generator
  */
class BGWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1656.0,
      height: 1779.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 56.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 1600.0,
            height: 1200.0,
            child: Rectangle15Widget1(),
          ),
          Positioned(
            left: 849.0,
            top: 311.0,
            right: null,
            bottom: null,
            width: 807.0,
            height: 1200.0,
            child: Rectangle18Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 718.0,
            height: 718.0,
            child: Ellipse3Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.01479633649190267;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 24.50273323059082;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.01377331828588579;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 24.50273323059082;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.338768115942029,
                      constraints.maxHeight * 0.7082630691399663,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget131(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 201.0,
            top: 1464.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 315.0,
            child: Ellipse4Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.10533231468016399;

              double height = constraints.maxHeight * 0.08094435075885328;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9761052523258228,
                      constraints.maxHeight * 0.3839235525576166,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget24(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.10533231468016399;

              double height = constraints.maxHeight * 0.08094435075885328;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.16028399628717543,
                      constraints.maxHeight * 0.7256885890949972,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget30(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 56.0,
            top: 1167.0,
            right: null,
            bottom: null,
            width: 1600.0,
            height: 854.0,
            child: Rectangle17Widget1(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.01636473798521475;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 27.100006103515625;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.015233263398503373;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 27.0999755859375;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.7107487922705314,
                      constraints.maxHeight * 0.3102866779089376,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget192(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.031582127446713654;

              double height = constraints.maxHeight * 0.029286119226259486;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.8176217931480223,
                      constraints.maxHeight * 0.8368869586363477,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget31(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
