import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaEllipse Ellipse 3
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 718.0,
      height: 718.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M718 359C718 557.27 557.27 718 359 718C160.73 718 0 557.27 0 359C0 160.73 160.73 0 359 0C557.27 0 718 160.73 718 359Z')
          ..color = Color.fromARGB(255, 80, 85, 100),
      ]),
    );
  }
}
