import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget23.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget21.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget19.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget22.dart';
import 'package:flutterapp/figma/thumb2widget/widgets/GroupWidget20.dart';

/* FigmaGroup Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-1.00, -0.00, 0.00, 0.00, 0.00, -1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 174.43031311035156,
          height: 144.0,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                children: [
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double width = constraints.maxWidth * 1.0;

                      double height =
                          constraints.maxHeight * 0.09056585364871556;

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                          alignment: Alignment.topLeft,
                          child: Container(
                            width: width,
                            height: height,
                            child: GroupWidget19(),
                          ),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double width = constraints.maxWidth * 1.0;

                      double height =
                          constraints.maxHeight * 0.09056585364871556;

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              constraints.maxHeight * 0.22641571362813315,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: Container(
                            width: width,
                            height: height,
                            child: GroupWidget20(),
                          ),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double width = constraints.maxWidth * 1.0;

                      double height =
                          constraints.maxHeight * 0.09056585364871556;

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              constraints.maxHeight * 0.4547189606560601,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: Container(
                            width: width,
                            height: height,
                            child: GroupWidget21(),
                          ),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double width = constraints.maxWidth * 1.0;

                      double height =
                          constraints.maxHeight * 0.09056585364871556;

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              constraints.maxHeight * 0.6811343299018012,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: Container(
                            width: width,
                            height: height,
                            child: GroupWidget22(),
                          ),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double width = constraints.maxWidth * 1.0;

                      double height =
                          constraints.maxHeight * 0.09056643644968669;

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              constraints.maxHeight * 0.90943357679579,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: Container(
                            width: width,
                            height: height,
                            child: GroupWidget23(),
                          ),
                        )
                      ]);
                    }),
                  )
                ]),
          ),
        ));
  }
}
