import 'package:flutter/material.dart';

/* FigmaRectangle img
    Autogenerated by FlutLab FTF Generator
  */
class ImgWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 454.0,
      height: 805.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/2eb027abf07dd45f73f4dd9718cc2282a88c1988.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2eb027abf07dd45f73f4dd9718cc2282a88c1988.png",
          color: null,
          fit: BoxFit.cover,
          width: 454.0,
          height: 805.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
