import 'package:flutter/material.dart';

/* FigmaRectangle img
    Autogenerated by FlutLab FTF Generator
  */
class ImgWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 453.0,
      height: 806.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/051b14b019e7394aed317617c82caad313b007a8.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/051b14b019e7394aed317617c82caad313b007a8.png",
          color: null,
          fit: BoxFit.cover,
          width: 453.0,
          height: 806.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
