import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget131 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 24.50273323059082,
      height: 24.50273323059082,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M12.5014 24.5014C5.70137 24.6014 0.101367 19.2014 0.00136681 12.5014C-0.0986332 5.70137 5.30137 0.101367 12.0014 0.00136681C18.8014 -0.0986332 24.4014 5.30137 24.5014 12.0014C24.6014 18.8014 19.2014 24.4014 12.5014 24.5014ZM12.2014 5.70136C8.60136 5.80136 5.70136 8.80136 5.70136 12.4014C5.80136 16.0014 8.80136 18.9014 12.4014 18.9014C16.0014 18.8014 18.9014 15.8014 18.9014 12.2014C18.8014 8.50136 15.8014 5.60136 12.2014 5.70136Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
