import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/GroupWidget15.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Rectangle15Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget50.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget111.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Rectangle17Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Ellipse3Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/GroupWidget14.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Ellipse4Widget.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/GroupWidget8.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/Rectangle18Widget.dart';

/* FigmaGroup BG
    Autogenerated by FlutLab FTF Generator
  */
class BGWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1656.0,
      height: 1826.869873046875,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 56.0,
            top: 313.0,
            right: null,
            bottom: null,
            width: 1600.0,
            height: 1200.0,
            child: Rectangle15Widget(),
          ),
          Positioned(
            left: 849.0,
            top: 311.0,
            right: null,
            bottom: null,
            width: 807.0,
            height: 1202.0,
            child: Rectangle18Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 718.0,
            height: 718.0,
            child: Ellipse3Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.01479633649190267;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 24.50273323059082;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.013412412997826098;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 24.50273323059082;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.338768115942029,
                      constraints.maxHeight * 0.6897042961787734,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget50(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 201.0,
            top: 1464.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 315.0,
            child: Ellipse4Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.10533231468016399;

              double height = constraints.maxHeight * 0.07882334813471696;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9761052523258228,
                      constraints.maxHeight * 0.3738635192778589,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget8(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.10533231468016399;

              double height = constraints.maxHeight * 0.07882334813471696;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.16028399628717543,
                      constraints.maxHeight * 0.7066732114022194,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget14(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 56.0,
            top: 1167.0,
            right: null,
            bottom: null,
            width: 1600.0,
            height: 854.0,
            child: Rectangle17Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.01636473798521475;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 27.100006103515625;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.014834102847588067;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 27.0999755859375;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.7107487922705314,
                      constraints.maxHeight * 0.30215616784974836,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget111(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.8095021270899381;

              double height = constraints.maxHeight * 0.29020862881420056;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.6134864696557971,
                      constraints.maxHeight * 1.0,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: GroupWidget15(),
                  ),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
