import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaEllipse Ellipse 4
    Autogenerated by FlutLab FTF Generator
  */
class Ellipse4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 315.0,
      height: 315.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M315 157.5C315 244.485 244.485 315 157.5 315C70.5152 315 0 244.485 0 157.5C0 70.5152 70.5152 0 157.5 0C244.485 0 315 70.5152 315 157.5Z')
          ..color = Color.fromARGB(204, 80, 85, 100),
      ]),
    );
  }
}
