import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget100.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget101.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget104.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget102.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget103.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget99.dart';

/* FigmaGroup Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(1.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00, 0.00,
            0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 174.43031311035156,
          height: 13.041482925415039,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                children: [
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476663096112353;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041566848754883;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0,
                              0, 0, 1, 0, 0, 0, 0, 1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget99(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476614983293917;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041482925415039;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              constraints.maxWidth * 0.18535859139664077,
                              constraints.maxHeight * 0.0000015309514406239184,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget100(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476614983293917;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041482925415039;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              constraints.maxWidth * 0.370716745404023,
                              constraints.maxHeight * 0.0000015309514406239184,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget101(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476663096112353;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041566848754883;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              constraints.maxWidth * 0.5545172031756209,
                              constraints.maxHeight * 0.0000015309514406239184,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget102(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476663096112353;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041566848754883;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              constraints.maxWidth * 0.7398751603578368,
                              constraints.maxHeight * 0.0000015309514406239184,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget103(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.07476614983293917;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          13.041482925415039;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 1.0;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          13.041482925415039;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              constraints.maxWidth * 0.9252337298850147,
                              constraints.maxHeight * 0.0000015309514406239184,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget104(),
                        )
                      ]);
                    }),
                  )
                ]),
          ),
        ));
  }
}
