import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget112.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/VectorWidget113.dart';

/* FigmaGroup Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.71, -0.71, 0.00, 0.00, 0.71, -0.71, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 1340.5355224609375,
          height: 530.1734008789062,
          child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                children: [
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.039014261222817995;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          52.30000305175781;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 0.09826974725089137;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          52.100006103515625;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(
                              scaleX,
                              0,
                              0,
                              0,
                              0,
                              scaleY,
                              0,
                              0,
                              0,
                              0,
                              1,
                              0,
                              0,
                              constraints.maxHeight * 0.9017303103106122,
                              0,
                              1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget112(),
                        )
                      ]);
                    }),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      double percentWidth = 0.03158172616233947;
                      double scaleX = (constraints.maxWidth * percentWidth) /
                          42.33642578125;
                      if (scaleX < percentWidth) {
                        scaleX = percentWidth;
                      }

                      double percentHeight = 0.07954855894200115;
                      double scaleY = (constraints.maxHeight * percentHeight) /
                          42.174530029296875;
                      if (scaleY < percentHeight) {
                        scaleY = percentHeight;
                      }

                      return Stack(children: [
                        Transform(
                          transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0,
                              0, 0, 1, 0, constraints.maxWidth * 1.0, 0, 0, 1),
                          alignment: Alignment.topLeft,
                          child: VectorWidget113(),
                        )
                      ]);
                    }),
                  )
                ]),
          ),
        ));
  }
}
