import 'package:flutter/material.dart';

/* FigmaRectangle img
    Autogenerated by FlutLab FTF Generator
  */
class ImgWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 453.0,
      height: 805.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/51333e0f73b33b82da0e77273b296cf798e3b4db.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/51333e0f73b33b82da0e77273b296cf798e3b4db.png",
          color: null,
          fit: BoxFit.cover,
          width: 453.0,
          height: 805.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
