import 'package:flutter/material.dart';

/* FigmaRectangle Rectangle 17
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: false,
      child: Transform(
          transform: Matrix4(1.00, 0.00, 0.00, 0.00, 0.00, -1.00, 0.00, 0.00,
              0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
          alignment: Alignment.topLeft,
          child: Container(
            width: 1600.0,
            height: 854.0,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: null,
                height: null,
                decoration: BoxDecoration(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
                child: null,
              ),
            ),
          )),
    );
  }
}
