import 'package:flutter/material.dart';

/* FigmaRectangle Rectangle 18
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 807.0,
      height: 1202.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 242, 242, 242),
          ),
          child: null,
        ),
      ),
    );
  }
}
