import 'package:flutter/material.dart';

/* FigmaRectangle Rectangle 15
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1600.0,
      height: 1200.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 37, 42, 55),
          ),
          child: null,
        ),
      ),
    );
  }
}
