import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget129 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.85515785217285,
      height: 6.061258316040039,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M17.6553 5.59676C16.8557 6.66281 13.1246 5.59678 8.86035 5.33027C4.59614 5.06376 0.864981 5.86326 0.0654409 4.79721C-0.201072 4.26418 0.331987 2.93164 1.93107 1.86559C3.53015 0.799532 6.19515 0 9.1268 0C12.0584 0.266513 14.4572 1.33255 16.0562 2.3986C17.6553 3.99769 18.1883 5.06373 17.6553 5.59676Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
