import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget81 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.041566848754883,
      height: 13.041482925415039,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.52083 13.0415C10.1221 13.0415 13.0416 10.1221 13.0416 6.52074C13.0416 2.91943 10.1221 0 6.52083 0C2.91951 0 0 2.91943 0 6.52074C0 10.1221 2.91951 13.0415 6.52083 13.0415Z')
          ..color = Color.fromARGB(204, 80, 85, 100),
      ]),
    );
  }
}
