import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget114 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 239.071533203125,
      height: 301.610107421875,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M28.6756 30.7803C58.2586 -8.13062 89.1742 -2.53384 110.762 6.79413C132.349 16.1221 146.741 39.8418 145.408 63.295C145.142 69.4248 143.81 76.0876 146.208 81.6844C150.206 90.7459 161.932 93.411 168.862 100.607C178.19 110.468 176.058 126.459 172.859 139.518C169.661 152.843 166.463 168.035 174.192 179.228C181.388 189.356 194.98 192.287 206.174 197.618C221.098 204.814 233.091 218.406 237.356 234.13C241.62 250.121 237.889 268.244 226.695 280.503C215.768 292.496 199.244 297.827 183.253 299.959C136.614 306.888 87.3087 291.697 52.3954 260.248C17.4821 228.533 -1.97343 180.827 0.158679 133.921')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
