import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget124 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.05337142944336,
      height: 5.168703079223633,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M18.9867 5.09822C18.4537 5.63125 14.7225 2.96614 9.65877 2.96614C4.59501 2.69963 0.597375 5.36476 0.0643482 4.83173C-0.202165 4.56522 0.330829 3.49916 2.19642 2.1666C3.7955 1.10054 6.72705 -0.232032 9.92522 0.034481C13.1234 0.034481 15.7886 1.36705 17.3877 2.69961C18.7203 3.49916 19.2533 4.56519 18.9867 5.09822Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
