import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget128 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 23.54309844970703,
      height: 6.715329647064209,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M23.5031 4.06562C22.9701 5.39818 17.9064 4.59864 11.7766 5.39818C5.64681 5.93121 0.849509 7.5303 0.0499685 6.19773C-0.216545 5.66471 0.58306 4.33211 2.44865 2.99954C4.31425 1.66697 7.51238 0.33443 11.2436 0.0679167C14.9748 -0.198597 18.173 0.33443 20.3051 1.40048C22.7037 2.20002 23.7696 3.53259 23.5031 4.06562Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
