import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget119 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 12.259553909301758,
      height: 12.259593963623047,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M6.12978 12.2596C9.51518 12.2596 12.2596 9.51518 12.2596 6.12978C12.2596 2.74438 9.51518 0 6.12978 0C2.74438 0 0 2.74438 0 6.12978C0 9.51518 2.74438 12.2596 6.12978 12.2596Z')
          ..color = Color.fromARGB(255, 250, 250, 250),
      ]),
    );
  }
}
