import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget123 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 9.594581604003906,
      height: 9.084029197692871,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M9.59458 4.28682C9.59458 6.68544 7.46234 8.81752 4.79721 9.08403C2.13208 9.08403 0 7.21846 0 4.81984C0 2.42122 2.13208 0.289103 4.79721 0.0225891C7.46234 -0.243924 9.59458 1.8882 9.59458 4.28682Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
