import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 91
    Autogenerated by FlutLab FTF Generator
  */
class XMLID91Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.85, 0.52, 0.00, 0.00, -0.52, -0.85, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 24.519107818603516,
          height: 1.5990968942642212,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M12.2596 1.5991C19.0304 1.5991 24.5191 1.24116 24.5191 0.799589C24.5191 0.358015 19.0304 0 12.2596 0C5.48875 0 0 0.358015 0 0.799589C0 1.24116 5.48875 1.5991 12.2596 1.5991Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
