import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 99
    Autogenerated by FlutLab FTF Generator
  */
class XMLID99Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.51, 0.86, 0.00, 0.00, -0.86, -0.51, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 21.85413360595703,
          height: 1.5990561246871948,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M10.927 1.59906C16.9618 1.59906 21.8541 1.24112 21.8541 0.799548C21.8541 0.357974 16.9618 0 10.927 0C4.89214 0 0 0.357974 0 0.799548C0 1.24112 4.89214 1.59906 10.927 1.59906Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
