import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 71
    Autogenerated by FlutLab FTF Generator
  */
class XMLID71Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.55324935913086,
      height: 22.674396514892578,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.0126093 0.0111741C0.279123 -0.255339 4.80985 4.27545 9.34058 10.4053C13.8713 16.8016 16.803 22.3983 16.5365 22.6648C16.27 22.9313 12.8052 17.6011 8.27446 11.2048C3.74373 5.07496 -0.253904 0.277688 0.0126093 0.0111741Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
