import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 139
    Autogenerated by FlutLab FTF Generator
  */
class XMLID139Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.09, 1.00, 0.00, 0.00, -1.00, -0.09, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 25.05232810974121,
          height: 1.5990968942642212,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M12.5262 1.5991C19.4442 1.5991 25.0523 1.24116 25.0523 0.799589C25.0523 0.358015 19.4442 0 12.5262 0C5.60817 0 0 0.358015 0 0.799589C0 1.24116 5.60817 1.5991 12.5262 1.5991Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
