import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 63
    Autogenerated by FlutLab FTF Generator
  */
class XMLID63Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.50, 0.87, 0.00, 0.00, -0.87, -0.50, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 31.44855308532715,
          height: 1.5990968942642212,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M15.7242 1.5991C24.4085 1.5991 31.4486 1.24108 31.4486 0.799508C31.4486 0.357934 24.4085 0 15.7242 0C7.03991 0 0 0.357934 0 0.799508C0 1.24108 7.03991 1.5991 15.7242 1.5991Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
