import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 127
    Autogenerated by FlutLab FTF Generator
  */
class XMLID127Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 17.33885955810547,
      height: 16.55193328857422,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0.0154993C0.266513 -0.251014 4.79734 2.94715 9.59458 7.47788C14.3918 12.0086 17.5899 16.5393 17.3234 16.5393C17.0569 16.8058 13.3257 12.8082 8.52846 8.27743C3.99773 4.01322 0 0.282013 0 0.0154993Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
