import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID75Widget1.dart';

/* FigmaGroup XMLID 74
    Autogenerated by FlutLab FTF Generator
  */
class XMLID74Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 19.800996780395508,
      height: 10.928079605102539,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.076767784769432;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 21.321075439453125;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.146329176950502;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990968942642212;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9640298899235895,
                      constraints.maxHeight * 0.9999999127317561,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID75Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
