import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID91Widget1.dart';

/* FigmaGroup XMLID 90
    Autogenerated by FlutLab FTF Generator
  */
class XMLID90Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.720687866210938,
      height: 14.20750904083252,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.1288366174050062;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 24.519107818603516;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.11255293870786223;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990968942642212;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 1.0,
                      constraints.maxHeight * 0.0958637662590208,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID91Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
