import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 147
    Autogenerated by FlutLab FTF Generator
  */
class XMLID147Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.1229305267334,
      height: 7.897507667541504,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M16.1229 7.89751C15.8564 7.89751 15.3234 7.09796 13.9909 5.76539C12.6583 4.43283 11.0591 2.56723 8.39398 1.76769C5.99536 0.968151 3.33032 1.7677 1.99775 2.56724C0.665185 3.63329 0.398639 4.69936 0.132125 4.69936C-0.134388 4.69936 -0.134388 3.36677 1.46469 1.76769C2.79726 0.435124 5.99539 -0.63093 8.92704 0.435124C11.8587 1.50118 13.7243 3.63329 14.7904 5.23237C15.8564 6.56494 16.1229 7.63099 16.1229 7.89751Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
