import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 111
    Autogenerated by FlutLab FTF Generator
  */
class XMLID111Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.36, 0.93, 0.00, 0.00, -0.93, -0.36, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 23.986204147338867,
          height: 1.5990968942642212,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M11.9931 1.5991C18.6167 1.5991 23.9862 1.24112 23.9862 0.799548C23.9862 0.357975 18.6167 0 11.9931 0C5.36949 0 0 0.357975 0 0.799548C0 1.24112 5.36949 1.5991 11.9931 1.5991Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
