import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID139Widget1.dart';

/* FigmaGroup XMLID 138
    Autogenerated by FlutLab FTF Generator
  */
class XMLID138Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 3.905040979385376,
      height: 25.09223175048828,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 6.415381616221671;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 25.05232810974121;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.06372876315527827;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990968942642212;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 1.0000097075944343,
                      constraints.maxHeight * 0.005884195192890365,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID139Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
