import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID95Widget1.dart';

/* FigmaGroup XMLID 94
    Autogenerated by FlutLab FTF Generator
  */
class XMLID94Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 11.626169204711914,
      height: 21.821083068847656,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 2.017272360531878;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 23.453149795532227;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.07328219636114824;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990968942642212;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.8760999373140111,
                      constraints.maxHeight * 1.0,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID95Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
