import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 165
    Autogenerated by FlutLab FTF Generator
  */
class XMLID165Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.084625244140625,
      height: 13.858691215515137,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M20.0846 0.799548C20.0846 1.06606 18.4855 0.799524 16.3534 1.06604C13.9548 1.33255 11.0232 2.13211 8.09152 3.9977C5.15987 5.8633 3.0278 8.52841 1.96174 10.394C0.89569 12.2596 0.36263 13.8587 0.0961168 13.8587C-0.170397 13.8587 0.0961819 12.2596 1.16224 10.1275C2.22829 7.99541 4.09385 5.06373 7.29201 2.93162C10.4902 0.799516 13.9548 0 16.3534 0C18.4855 0 20.0846 0.533035 20.0846 0.799548Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
