import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID39Widget1.dart';

/* FigmaGroup XMLID 38
    Autogenerated by FlutLab FTF Generator
  */
class XMLID38Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.515406608581543,
      height: 13.814458847045898,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.236770628067974;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 19.18899917602539;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.11575235355883225;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990561246871948;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.9999998770674413,
                      constraints.maxHeight * 0.08725581632955967,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID39Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
