import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 119
    Autogenerated by FlutLab FTF Generator
  */
class XMLID119Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.85, -0.52, 0.00, 0.00, 0.52, -0.85, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 20.78801727294922,
          height: 1.5990968942642212,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M10.3941 1.5991C16.1346 1.5991 20.788 1.24112 20.788 0.799548C20.788 0.357975 16.1346 0 10.3941 0C4.65363 0 0 0.357975 0 0.799548C0 1.24112 4.65363 1.5991 10.3941 1.5991Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
