import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID131Widget1.dart';

/* FigmaGroup XMLID 130
    Autogenerated by FlutLab FTF Generator
  */
class XMLID130Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 20.656808853149414,
      height: 20.042766571044922,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 1.3159941854737118;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 27.184240341186523;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.07978220566602291;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990561246871948;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 1.000000923351059,
                      constraints.maxHeight * 0.05736512034146344,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID131Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
