import 'package:flutter/material.dart';
import 'package:flutterapp/figma/thumb1widget/widgets/XMLID135Widget1.dart';

/* FigmaGroup XMLID 134
    Autogenerated by FlutLab FTF Generator
  */
class XMLID134Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 8.531475067138672,
      height: 22.858989715576172,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 2.7490146324014355;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 23.453149795532227;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.06995483676929924;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 1.5990968942642212;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.17886847606165954,
                      constraints.maxHeight * -2.937401440693855e-7,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: XMLID135Widget1(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
