import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 83
    Autogenerated by FlutLab FTF Generator
  */
class XMLID83Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.288299560546875,
      height: 16.288137435913086,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.0126088 16.2699C-0.253905 16.0034 3.74389 12.8052 8.27462 8.27446C12.8054 3.74373 15.737 -0.253904 16.27 0.0126093C16.5365 0.279123 13.8713 4.80985 9.34058 9.34058C4.80985 13.8713 0.279122 16.5364 0.0126088 16.2699Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
