import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 131
    Autogenerated by FlutLab FTF Generator
  */
class XMLID131Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(-0.72, 0.69, 0.00, 0.00, -0.69, -0.72, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: Container(
          width: 27.184240341186523,
          height: 1.5990561246871948,
          child: SvgWidget(painters: [
            SvgPathPainter.fill()
              ..addPath(
                  'M13.5921 1.59906C21.0989 1.59906 27.1842 1.24112 27.1842 0.799548C27.1842 0.357974 21.0989 0 13.5921 0C6.08536 0 0 0.357974 0 0.799548C0 1.24112 6.08536 1.59906 13.5921 1.59906Z')
              ..color = Color.fromARGB(255, 54, 58, 68),
          ]),
        ));
  }
}
