import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector XMLID 115
    Autogenerated by FlutLab FTF Generator
  */
class XMLID115Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.303870677947998,
      height: 20.267606735229492,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.0226884 0.012567C0.289202 -0.253947 3.22091 3.74377 5.08651 9.60707C7.21862 15.2039 7.4851 20.2676 7.21858 20.2676C6.68556 20.2676 5.88605 15.7368 3.75394 10.14C1.88835 4.27675 -0.243825 0.012567 0.0226884 0.012567Z')
          ..color = Color.fromARGB(255, 54, 58, 68),
      ]),
    );
  }
}
