import 'package:flutter/material.dart';
import 'package:flutterapp/figma/splash1widget/widgets/IconWidget3.dart';
import 'package:flutterapp/figma/splash1widget/widgets/TextWidget9.dart';
import 'package:flutterapp/figma/splash1widget/widgets/Frame1Widget.dart';
import 'package:flutterapp/figma/splash1widget/widgets/AFPesanWidget.dart';

/* FigmaGroup logo
    Autogenerated by FlutLab FTF Generator
  */
class LogoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 272.0,
      height: 140.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 96.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 113.0,
            height: 35.0,
            child: AFPesanWidget(),
          ),
          Positioned(
            left: 52.0,
            top: 43.0,
            right: null,
            bottom: null,
            width: 35.0,
            height: 35.0,
            child: IconWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 100.0,
            right: null,
            bottom: null,
            width: 272.0,
            height: 40.0,
            child: TextWidget9(),
          ),
          Positioned(
            left: 142.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 100.0,
            child: Frame1Widget(),
          )
        ]),
      ),
    );
  }
}
