import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget44 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 29.166669845581055,
      height: 29.166669845581055,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M26.25 0L2.91667 0C1.3125 0 0.0145833 1.3125 0.0145833 2.91667L0 29.1667L5.83333 23.3333L26.25 23.3333C27.8542 23.3333 29.1667 22.0208 29.1667 20.4167L29.1667 2.91667C29.1667 1.3125 27.8542 0 26.25 0ZM23.3333 17.5L5.83333 17.5L5.83333 14.5833L23.3333 14.5833L23.3333 17.5ZM23.3333 13.125L5.83333 13.125L5.83333 10.2083L23.3333 10.2083L23.3333 13.125ZM23.3333 8.75L5.83333 8.75L5.83333 5.83333L23.3333 5.83333L23.3333 8.75Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
