import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/BoundsWidget3.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/ShapeWidget2.dart';

/* FigmaGroup cellular
    Autogenerated by FlutLab FTF Generator
  */
class CellularWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.0,
      height: 16.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 16.0,
            child: BoundsWidget3(),
          ),
          Positioned(
            left: 0.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 14.0,
            height: 14.0,
            child: ShapeWidget2(),
          )
        ]),
      ),
    );
  }
}
