import 'package:flutter/material.dart';

/* FigmaText 12:30
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab1230Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''12:30''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
