import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/TextWidget2.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/RectangleWidget1.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/DeliveredWidget.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/TextWidget1.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/Friday1523Widget1.dart';

/* FigmaGroup #2
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 288.0,
      height: 169.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 88.0,
            right: null,
            bottom: null,
            width: 252.0,
            height: 58.0,
            child: RectangleWidget1(),
          ),
          Positioned(
            left: 16.0,
            top: 97.0,
            right: null,
            bottom: null,
            width: 220.0,
            height: 40.0,
            child: TextWidget1(),
          ),
          Positioned(
            left: 68.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 220.0,
            height: 40.0,
            child: TextWidget2(),
          ),
          Positioned(
            left: 32.0,
            top: 59.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 16.0,
            child: Friday1523Widget1(),
          ),
          Positioned(
            left: 198.0,
            top: 153.0,
            right: null,
            bottom: null,
            width: 46.0,
            height: 16.0,
            child: DeliveredWidget(),
          )
        ]),
      ),
    );
  }
}
