import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/BaseWidget.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/ContentWidget.dart';

/* FigmaGroup Input
    Autogenerated by FlutLab FTF Generator
  */
class InputWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 75.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 75.0,
            child: BaseWidget(),
          ),
          Positioned(
            left: 16.0,
            top: 25.0,
            right: null,
            bottom: null,
            width: 327.0,
            height: 25.0,
            child: ContentWidget(),
          )
        ]),
      ),
    );
  }
}
