import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector insertion mark
    Autogenerated by FlutLab FTF Generator
  */
class InsertionmarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 1.0,
      height: 20.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 0L0 20L1 20L1 0L0 0Z')
          ..color = Color.fromARGB(51, 0, 0, 0),
      ]),
    );
  }
}
