import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class RectangleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 196.0,
      height: 40.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.95431 8.9543 0 20 0L176 0C187.046 0 196 8.95431 196 20L196 20C196 31.0457 187.046 40 176 40L20 40C8.95431 40 0 31.0457 0 20L0 20Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
