import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Rectangle
    Autogenerated by FlutLab FTF Generator
  */
class RectangleWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 270.0,
      height: 84.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 20C0 8.9543 8.95431 0 20 0L250 0C261.046 0 270 8.95431 270 20L270 64C270 75.0457 261.046 84 250 84L20 84C8.95431 84 0 75.0457 0 64L0 20Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
