import 'package:flutter/material.dart';

/* FigmaRectangle Rectangle 9
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 129.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
          child: null,
        ),
      ),
    );
  }
}
