import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Shape
    Autogenerated by FlutLab FTF Generator
  */
class ShapeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.0,
      height: 14.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M0 14L14 14L14 0L0 14Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
