import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/InsertionmarkWidget.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/InputtexWidget.dart';

/* FigmaGroup Text
    Autogenerated by FlutLab FTF Generator
  */
class TextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 178.0,
      height: 25.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 1.0,
            height: 20.0,
            child: InsertionmarkWidget(),
          ),
          Positioned(
            left: 1.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 177.0,
            height: 24.0,
            child: InputtexWidget(),
          )
        ]),
      ),
    );
  }
}
