import 'package:flutter/material.dart';

/* FigmaText text
    Autogenerated by FlutLab FTF Generator
  */
class TextWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Skrng yuk, ke nasi goreng yang disidang aja , tempat favorit kita
 jemput aku skrng ya!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3333333333333333,
        fontSize: 15.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
