import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/AppbarbgWidget.dart';
import 'package:flutterapp/figma/pesan1widget/widgets/AppbarcontentsWidget.dart';

/* FigmaGroup Tool bar
    Autogenerated by FlutLab FTF Generator
  */
class ToolbarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 80.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 80.0,
            child: AppbarbgWidget(),
          ),
          Positioned(
            left: 16.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 133.0,
            height: 24.0,
            child: AppbarcontentsWidget(),
          )
        ]),
      ),
    );
  }
}
