import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/ShapeWidget12.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/BoundsWidget13.dart';

/* FigmaGroup battery
    Autogenerated by FlutLab FTF Generator
  */
class BatteryWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.0,
      height: 16.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 16.0,
            child: BoundsWidget13(),
          ),
          Positioned(
            left: 3.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 9.0,
            height: 14.0,
            child: ShapeWidget12(),
          )
        ]),
      ),
    );
  }
}
