import 'package:flutter/material.dart';

/* FigmaVector bounds
    Autogenerated by FlutLab FTF Generator
  */
class BoundsWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.0,
      height: 16.0,
      child: null,
    );
  }
}
