import 'package:flutter/material.dart';

/* FigmaText 27 Mar, 2020
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab27Mar2020Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''27 Mar, 2020''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 2.0,
        fontSize: 10.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
