import 'package:flutter/material.dart';

/* FigmaText G-123123 is your Google verification...
    Autogenerated by FlutLab FTF Generator
  */
class G123123isyourGoogleverificationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''G-123123 is your Google verification...''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.6666666666666667,
        fontSize: 12.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
