import 'package:flutter/material.dart';

/* FigmaText I
    Autogenerated by FlutLab FTF Generator
  */
class IWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''I''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 0.9090909090909091,
        fontSize: 22.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
