import 'package:flutter/material.dart';

/* FigmaText Kode verifikasi FB-12345
    Autogenerated by FlutLab FTF Generator
  */
class KodeverifikasiFB12345Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Kode verifikasi FB-12345''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.6666666666666667,
        fontSize: 12.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
