import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/FlutLab2Widget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/FlutLab3Widget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/PesanTerbaruWidget.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/FlutLab1Widget2.dart';

/* FigmaGroup Recent Msg
    Autogenerated by FlutLab FTF Generator
  */
class RecentMsgWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Pesan1Widget'),
      child: Container(
        width: 344.0,
        height: 224.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 0.0,
                  top: 27.0,
                  right: null,
                  bottom: null,
                  width: 344.0,
                  height: 65.0,
                  child: FlutLab1Widget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 93.0,
                  right: null,
                  bottom: null,
                  width: 344.0,
                  height: 65.0,
                  child: FlutLab2Widget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 159.0,
                  right: null,
                  bottom: null,
                  width: 344.0,
                  height: 65.0,
                  child: FlutLab3Widget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 79.0,
                  height: 20.0,
                  child: PesanTerbaruWidget(),
                )
              ]),
        ),
      ),
    );
  }
}
