import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaVector Search bg
    Autogenerated by FlutLab FTF Generator
  */
class SearchbgWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 343.9094543457031,
      height: 48.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M2.00001 0C0.895438 0 0 0.895431 0 2L0 46C0 47.1046 0.895431 48 2 48L341.909 48C343.014 48 343.909 47.1046 343.909 46L343.909 2C343.909 0.895431 343.014 0 341.909 0L2.00001 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
        SvgPathPainter.stroke(
          1.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M-1 2L-1 46L1 46L1 2L-1 2ZM2 49L341.909 49L341.909 47L2 47L2 49ZM344.909 46L344.909 2L342.909 2L342.909 46L344.909 46ZM341.909 -1L2.00001 -1L2.00001 1L341.909 1L341.909 -1ZM344.909 2C344.909 0.343147 343.566 -1 341.909 -1L341.909 1C342.462 1 342.909 1.44772 342.909 2L344.909 2ZM341.909 49C343.566 49 344.909 47.6569 344.909 46L342.909 46C342.909 46.5523 342.462 47 341.909 47L341.909 49ZM-1 46C-1 47.6569 0.343145 49 2 49L2 47C1.44772 47 1 46.5523 1 46L-1 46ZM1 2C1 1.44772 1.44772 1 2.00001 1L2.00001 -1C0.343158 -1 -1 0.343141 -1 2L1 2Z')
          ..setLinearGradient(
            startX: 1.1309231259286379,
            startY: 0.0,
            endX: 1.1309231259286379,
            endY: 47.68431045230872,
            colors: [
              Color.fromARGB(0, 0, 0, 0),
              Color.fromARGB(0, 0, 0, 0),
              Color.fromARGB(10, 0, 0, 0)
            ],
            colorStops: [0.0, 0.800000011920929, 1.0],
          ),
        SvgPathPainter.stroke(
          1.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M-1 2L-1 46L1 46L1 2L-1 2ZM2 49L341.909 49L341.909 47L2 47L2 49ZM344.909 46L344.909 2L342.909 2L342.909 46L344.909 46ZM341.909 -1L2.00001 -1L2.00001 1L341.909 1L341.909 -1ZM344.909 2C344.909 0.343147 343.566 -1 341.909 -1L341.909 1C342.462 1 342.909 1.44772 342.909 2L344.909 2ZM341.909 49C343.566 49 344.909 47.6569 344.909 46L342.909 46C342.909 46.5523 342.462 47 341.909 47L341.909 49ZM-1 46C-1 47.6569 0.343145 49 2 49L2 47C1.44772 47 1 46.5523 1 46L-1 46ZM1 2C1 1.44772 1.44772 1 2.00001 1L2.00001 -1C0.343158 -1 -1 0.343141 -1 2L1 2Z')
          ..setLinearGradient(
            startX: 6.340922195323981,
            startY: 1.0477688544816142,
            endX: 6.340922195323981,
            endY: 47.27774327635604,
            colors: [
              Color.fromARGB(255, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255),
              Color.fromARGB(0, 255, 255, 255)
            ],
            colorStops: [0.0, 0.20000000298023224, 1.0],
          ),
      ]),
    );
  }
}
