import 'package:flutter/material.dart';

/* FigmaText Search in your city
    Autogenerated by FlutLab FTF Generator
  */
class SearchinyourcityWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''4388 Pesan''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.5,
        fontSize: 16.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 54, 58, 68),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
