import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* FigmaBooleanOperation Shape
    Autogenerated by FlutLab FTF Generator
  */
class ShapeWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 18.045255661010742,
      height: 14.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 3.01593L9.02263 14L18.0453 3.01593C15.5344 1.12256 12.4096 0 9.02263 0C5.63564 0 2.51085 1.12256 0 3.01593Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
