import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/BoundsWidget12.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/TimeWidget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/CellularWidget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/WifiWidget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/BatteryWidget2.dart';

/* FigmaGroup Status bar contents
    Autogenerated by FlutLab FTF Generator
  */
class StatusbarcontentsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 118.0,
      height: 24.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 118.0,
            height: 24.0,
            child: BoundsWidget12(),
          ),
          Positioned(
            left: 74.0,
            top: 3.0,
            right: null,
            bottom: null,
            width: 36.0,
            height: 17.0,
            child: TimeWidget2(),
          ),
          Positioned(
            left: 55.0,
            top: 4.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 16.0,
            child: BatteryWidget2(),
          ),
          Positioned(
            left: 35.0,
            top: 4.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 16.0,
            child: CellularWidget2(),
          ),
          Positioned(
            left: 14.977372169494629,
            top: 4.0,
            right: null,
            bottom: null,
            width: 18.045255661010742,
            height: 16.0,
            child: WifiWidget2(),
          )
        ]),
      ),
    );
  }
}
