import 'package:flutter/material.dart';

/* FigmaText text
    Autogenerated by FlutLab FTF Generator
  */
class TextWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Pesan''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 18.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
