import 'package:flutter/material.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/AppbarbgWidget2.dart';
import 'package:flutterapp/figma/pesanwidget/widgets/AppbarcontentsWidget2.dart';

/* FigmaGroup Tool bar
    Autogenerated by FlutLab FTF Generator
  */
class ToolbarWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360.0,
      height: 112.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 112.0,
            child: AppbarbgWidget2(),
          ),
          Positioned(
            left: 155.0,
            top: 40.0,
            right: null,
            bottom: null,
            width: 191.0,
            height: 24.0,
            child: AppbarcontentsWidget2(),
          )
        ]),
      ),
    );
  }
}
