import 'package:flutter/material.dart';

/* FigmaText yesterday 4:56 PM
    Autogenerated by FlutLab FTF Generator
  */
class Yesterday456PMWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''yesterday 4:56 PM''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.right,
      style: TextStyle(
        height: 2.0,
        fontSize: 10.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
